/************************************************************
  File: create_fact.sql
  Project: ProjectFinance_DW
  Author: Fahimeh Latifi
  Description: Create Fact table for Project-Based
               Financial Data Warehouse (OLAP)
               Tracks financial KPIs for projects

************************************************************/

-- =========================================================
-- Fact Table: Fact_ProjectFinance
-- Description: Stores financial metrics and KPIs for each project,
-- linking to dimensions: Project, Employee, Task, Time, CostCenter
-- =========================================================
CREATE TABLE Fact_ProjectFinance (
    Project_ID INT,                         -- FK to Dim_Project
    Employee_ID INT,                        -- FK to Dim_Employee
    Task_ID INT,                            -- FK to Dim_Task
    Time_ID INT,                            -- FK to Dim_Time
    Cost_Center_ID INT,                      -- FK to Dim_CostCenter

    Hours_Worked DECIMAL(10,2),             -- Number of hours worked
    Labor_Cost DECIMAL(12,2),               -- Cost of labor
    Expense_Amount DECIMAL(12,2),           -- Direct expenses
    Revenue_Amount DECIMAL(12,2),           -- Revenue generated by project
    Profit DECIMAL(12,2),                   -- Profit = Revenue - (Labor + Expense)
    Progress_Percent DECIMAL(5,2),          -- Project progress percentage

    -- =====================================================
    -- Foreign key constraints to ensure referential integrity
    -- =====================================================
    CONSTRAINT FK_Project FOREIGN KEY (Project_ID)
        REFERENCES Dim_Project(Project_ID),
    CONSTRAINT FK_Employee FOREIGN KEY (Employee_ID)
        REFERENCES Dim_Employee(Employee_ID),
    CONSTRAINT FK_Task FOREIGN KEY (Task_ID)
        REFERENCES Dim_Task(Task_ID),
    CONSTRAINT FK_Time FOREIGN KEY (Time_ID)
        REFERENCES Dim_Time(Time_ID),
    CONSTRAINT FK_CostCenter FOREIGN KEY (Cost_Center_ID)
        REFERENCES Dim_CostCenter(Cost_Center_ID)
);